name: Scheduled Multi-Job Workflow

# Workflow Triggers
on:
  push:

jobs:

  # -----------------------------------------
  # JOB 1
  # -----------------------------------------
  system-info:
    name: System Information Job
    runs-on: ubuntu-latest

    steps:

      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Step-3
        run: |
          pwd
          ls -latr
          hostname










