name: Scheduled Multi-Job Workflow

# Workflow Triggers
on:
  push:

jobs:

  # -----------------------------------------
  # JOB 1
  # -----------------------------------------
  system-info:
    name: System Information Job
    runs-on: ubuntu-latest

    steps:

      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Step-3
        run: |
          echo "pwd" >> myartifact.txt

          mkdir artifacts

          ls -latr >> artifacts/lists.txt

          hostname >> artifacts/hostname.txt

      - name: Upload Single Artifact
        uses: actions/upload-artifact@v4
        with:
          name: single_file
          path: ./myartifact.txt

      - name: Upload Artifact Directory
        uses: actions/upload-artifact@v4
        with:
          name: directory_artifacts
          path: artifacts/

      - name: Upload Multiple Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multiple_artifacts
          path: |
            ./myartifact.txt
            artifacts/

      - name: Upload Artifacts With Exclusions
        uses: actions/upload-artifact@v4
        with:
          name: filtered_artifacts
          path: |
            ./myartifact.txt
            artifacts/
            !**/hostname.txt
 # -----------------------------------------
  # JOB 2
  # -----------------------------------------
  system-info:
    name: job2
    runs-on: ubuntu-latest

    steps:

      - name: Checking the current directory
        run: |
          pwd
          ls -ltr
          hostname

      - name: Download single archifacts 
        uses: actions/download-artifact@v3.1.0
        with:
           name: single_file
       - name: Checking the current directory post download
        run: |
          pwd
          ls -ltr
          hostname









        
